name = "onyxcollaborative-check-domain"
main = "check.js"
type = "javascript"
account_id = "60ea56fd96c28f2ee0386655a8797600"

# Optionally, if using routes:
# routes = ["https://your-custom-domain.com/*"]
# zone_id = "your_zone_id_here"
